env:
  browser: true
  es2021: true
ignorePatterns:
  - '**/*.js'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
  project: [ './tsconfig.json' ]
plugins:
  - '@typescript-eslint'
rules:
  {
    '@typescript-eslint/no-unused-vars': 'error',
    '@typescript-eslint/explicit-module-boundary-types': 'off',
    '@typescript-eslint/no-floating-promises': 'error',
    '@typescript-eslint/no-require-imports': 'error',
    'no-multi-spaces': 'warn',
    'eqeqeq': 'error',
  }
overrides:
  - files:
      - '**/*.spec.ts'
      - '**/__mocks__/*.ts'
    rules:
      '@typescript-eslint/no-explicit-any': 'off'
      '@typescript-eslint/no-non-null-assertion': 'off'