name: Continuous Integration

on: [ pull_request ]

jobs:
  unit-tests:
    name: Unit tests
    needs: compile-and-lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.10'